extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: localhost:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  logging:
    verbosity: detailed
  loggregator:
    ca_cert: /Users/mkocher/workspace/opentelemetry-collector/exporter/loggregatorexporter/testdata/test_cert.pem
    cert: /Users/mkocher/workspace/opentelemetry-collector/exporter/loggregatorexporter/testdata/test_cert.pem
    key: /Users/mkocher/workspace/opentelemetry-collector/exporter/loggregatorexporter/testdata/test_key.pem
    endpoint: example.com:1234

connectors:
  logmetrics:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [ memory_limiter, batch]
      exporters: [logmetrics]
    metrics:
      receivers: [logmetrics]
      processors: [ memory_limiter, batch]
      exporters: [logging, loggregator]

  extensions: [memory_ballast, zpages]
